### ISSUE TITLE
第三方模拟api

### ISSUE THREAD

**Issue by pretenderlu** [godruoyi/tg_bing_dalle#1]
项目可以使用第三方模拟的chatgpt api吗

**Comment by godruoyi** [comment]
hi @pretenderlu, 目前对 openAI API 是支持的，你指的第三方 API 是是哪个平台啊，可以告诉我让我试试吗？

如果他的返回结构/Request 参数和 OpenAI API 是一致的的话，我觉得是可以的，

**Comment by pretenderlu** [comment]
> hi @pretenderlu, 目前对 openAI API 是支持的，你指的第三方 API 是是哪个平台啊，可以告诉我让我试试吗？
> 
> 如果他的返回结构/Request 参数和 OpenAI API 是一致的的话，我觉得是可以的，

比如项目[pandora](https://github.com/zhile-io/pandora)中的[fakeopen](https://github.com/zhile-io/pandora/blob/master/doc/fakeopen.md#fakeopen-api-%E6%96%87%E6%A1%A3)

**Comment by godruoyi** [comment]
hi @pretenderlu 我看了你提供的平台，它看起来不支持 [DALL·E](https://platform.openai.com/docs/models/dall-e) 模型，也没有能通过文字生成图片的 API 如 `/v1/images/generations`，所有应该是不可以的。

其实你可以直接使用 Bing DALL E3，只需要提供一个 Cookie 就可以了。现在 OpenAI 开放的 DALLE 模型也只是 DALLE2，画图能力一般。

哦对了，目前这个小工具还支持使用百度千帆，虽然生成的图片不咋地，但也可以试试。

**Comment by pretenderlu** [comment]
> hi @pretenderlu 我看了你提供的平台，它看起来不支持 [DALL·E](https://platform.openai.com/docs/models/dall-e) 模型，也没有能通过文字生成图片的 API 如 `/v1/images/generations`，所有应该是不可以的。
> 
> 其实你可以直接使用 Bing DALL E3，只需要提供一个 Cookie 就可以了。现在 OpenAI 开放的 DALLE 模型也只是 DALLE2，画图能力一般。
> 
> 哦对了，目前这个小工具还支持使用百度千帆，虽然生成的图片不咋地，但也可以试试。

好嘞~~
